### ISSUE TITLE
Event listeners are not re-enabled on play()

### ISSUE THREAD

**Issue by jaredpike** [tizzle/aframe-orbit-controls-component#1]
This is a bug that happens when you toggle between two cameras. Once the orbital camera is paused and played again, you lose the ability to pan, zoom, etc, because the event listeners are not added on play.

**Comment by tizzle** [comment]
@jaredpike: Thanks for catching this!
I'm currently on vacation, but will have a look at it next week.

**Comment by tizzle** [comment]
Hey @jaredpike,

i think i fixed this issue, feel free to have a look.
