### ISSUE TITLE
look-cam in VR mode

### ISSUE THREAD

**Issue by morandd** [tizzle/aframe-orbit-controls-component#12]
Hi,

I'd like to make  an addition to this, that this controller morphs into a `look-control` on the `enter-vr` event. 

Currently I have written a camera juggler component to handle this switchover:
https://github.com/morandd/dans-aframe-camera-juggler/issues

Since `look-control` is built in to AFrame, I think it should be safe that orbit-controls morphs itself into look-controls when entering VR. I think I can code that up and submit a PR. Any thoughts/reactions before I begin?

**Comment by tizzle** [comment]
Hey @morandd,

i accepted you PR.
I will leave this open until i have finished looking into the look direction on switch issue and added an example.

Cheers

Till

**Comment by tizzle** [comment]
Hey @morandd,

i finally have a new release. I guess i fixed the position/rotation issue. Please have a look at how it is currently implemented.

We might want to pass another parameter to define the initial position for the look-controls, what do you think?

Cheers

Till

**Comment by morandd** [comment]
Wow, great, thanks for your work on this -- much appreciated.

I had paused on the camera stuff in my project while working on other aspects, but I'll get back to the cameras this week and will comment here if I find any issue.

For the initial position of the look-controls, I'd just hope for something intuitive. Like pitch & roll angle = 0, and yaw = point camera at target. 

the pitch=0 could be a bit important, because often orbit-cams are placed a bit over the target (God's eye perspective), so with some pitch angle. But in VR the pitch angle should match the head angle, ie. start at 0 when you put on the goggles.

**Comment by morandd** [comment]
@tizzle minor: rotateTo default should be [0, 0,0] not "0 0 0"; the latter throws a warning in the newest aframe build.

**Comment by tizzle** [comment]
Hey @morandd,

have you seen the latest version, i merged your PR. Are you alright with closing this?

Cheers

Till

**Comment by morandd** [comment]
havent noticed any issues
