### ISSUE TITLE
feature request - inverted zoom option

### ISSUE THREAD

**Issue by MannyMeadows** [tizzle/aframe-orbit-controls-component#16]
I'm seeking an option for inverted zoom, much like the aframe inspector.

Many users will find an inverted zoom much more intuitive.

Many thanks.

**Comment by tizzle** [comment]
Hey @MannyMeadows,

please have a look at the current version, inverted zoom is now implemented.
It is false by default and can be added have a look at the README or the basic example.

```
<a-entity
  id="camera"
  orbit-controls="
    invertZoom: true;
  "
>
</a-entity>
```

Hope it's what you were looking for!

Cheers

Till

**Comment by MannyMeadows** [comment]
That is exactly what I'm looking for.

Thanks for the quick turnaround!
