### ISSUE TITLE
Unknown camera type when sound entity added

### ISSUE THREAD

**Issue by jaredpike** [tizzle/aframe-orbit-controls-component#2]
When you add a sound to the scene, the ability to dollyIn/Out breaks. Using A-Frame 0.3.2. 

`Trying to dolly out: WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.`

**Comment by tizzle** [comment]
Hey @jaredpike ,

i cannot reproduce this issue. I upüdated Aframe to 0.3.2 and then followed the guides from the A-Frame website to add sound:

```
<a-entity
                id="river"
                geometry="primitive: plane"
                material="color: blue"
                position="-10 0 0"
                sound="src: url(river.mp3);
                autoplay: true">
            </a-entity>
```

When inserting this into a scene with an orbit-control-camera, dolly and zoom functions work fine. Sound works as well. 3D-Sound is awesome, i never tried it out before.

Can you double check that you used unique ids? Can you give me a code snippet of your implementation?

Thanks and kind regards

Till

**Comment by tizzle** [comment]
@jaredpike, were you able to check out if this works for you?

Best,

Till

**Comment by jaredpike** [comment]
Hey @tizzle, I sorted it out. Thanks!
