### ISSUE TITLE
README points to v0.1.8 on the CDN, but latest ver is 0.1.7

### ISSUE THREAD

**Issue by morandd** [tizzle/aframe-orbit-controls-component#24]
In README.md you point users to

http://cdn.rawgit.com/tizzle/aframe-orbit-controls-component/v0.1.8/dist/aframe-orbit-controls-component.min.js

but that gives a 404, and indeed it appears the latest version tag is 0.1.7. Fixing the URL to 0.1.7 works.

**Comment by tizzle** [comment]
@morandd,

i forgot to push the tag, sorry. Should be fixed now.
