### ISSUE TITLE
Does not work on A-Frame 0.7

### ISSUE THREAD

**Issue by HAZARDU5** [tizzle/aframe-orbit-controls-component#27]
I've just tried upgrading one of my demo scenes to A-Frame 0.7, and looks like the orbit controls component no longer registers clicks and drags on the scene. See demo:

https://hazardu5.github.io/aframe-workshop/examples/09/finish/

It broke somewhere between commit https://github.com/aframevr/aframe/commit/adabe788bb1a6f015a939f8fb84dd86365ce4565 and 0.7 release of A-Frame.

**Comment by HAZARDU5** [comment]
After further investigation, I narrowed down the offending commit to:

https://github.com/aframevr/aframe/commit/5214a16b9aa625463d5b6f2a315b5da8f8977ca5

It's likely that the change in here is causing a conflict in the way that `aframe-orbit-controls-component` is binding its event listeners.

**Comment by HAZARDU5** [comment]
I have a working fix for this - you need to swap out the event listener for `render-target-loaded` to `renderstart`. Then it will be able to bind events to the canvas correctly. Will do a PR once I've finished testing this out in my production project.

**Comment by HAZARDU5** [comment]
A fix is now available in PR #29

**Comment by tizzle** [comment]
Hey, i merged this now. New package is available at NPM:  
https://www.npmjs.com/package/aframe-orbit-controls-component-2

**Comment by kfarr** [comment]
Confirming yes this works on A-Frame 0.7.0 and 0.7.1, you can close this ticket

**Comment by tizzle** [comment]
Thanks for the confirmation, closing the issue now.
