### ISSUE TITLE
DollyDelta on Pan?

### ISSUE THREAD

**Issue by zcanter** [tizzle/aframe-orbit-controls-component#3]
Hello, great component.

I'm unable to pan with my mouse. I get an error that says "Can't find variable: dollyDelta". 

Thanks!

**Comment by tizzle** [comment]
Hay @zcanter i will take a look and get back to you, thanks for the catch.

**Comment by tizzle** [comment]
Hey @zcanter i just updated the controls.

You now should be able to pan with the right mouse button and arrow keys on desktop, or three finger swipe on touch devices. Feel free to give it a try and get back to me.

Cheers

Till

**Comment by zcanter** [comment]
Hi Till,

Works great! Thanks a lot, great work!

Closing the issue now.

Best,
Zac
