### ISSUE TITLE
would like to add support for trackpads (shift key as alternative to mouse button 3)

### ISSUE THREAD

**Issue by morandd** [tizzle/aframe-orbit-controls-component#5]
I'd like to add support for trackpads (just enter PAN mode on mousedown+event.isShift, since trackpads dont have 3 buttons).

Could you accept the outstanding PR so I can proceed. I don't want to start until there is a stable base to work from, since git merges are too complex for me to grok. thanks!

**Comment by morandd** [comment]
I think this is as simple as changing the line

else if ( event.button === this.mouseButtons.PAN )

to 

else if ( event.button === this.mouseButtons.PAN || (event.button===this.mouseButtons.ORBIT && event.isShift )

Then shift+trackpad single touch (aka mouse button 1) is the same as mouse3.

**Comment by tizzle** [comment]
Hey @morandd,

sorry for the delay, i just merged the open pull request from @HAZARDU5.
Feel free to rock!

Thanks for you contribution.

Cheers
